title: Levente Bajczi
logo: /assets/img/leventebajczi.jpg
description: Computer scientist, PhD Student
website1: https://ftsrg.mit.bme.hu
affiliation1: Critical Systems Research Group
title1: PhD Student
scholar: 
mail: levente.bajczi@edu.bme.hu
linkedin: leventebajczi
dblp: https://dblp.org/pid/253/1882
theme: jekyll-theme-minimal
